// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PichangasApi.Data;

#nullable disable

namespace PichangasApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PichangasApi.Models.Pichanga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Publica")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Pichangas");
                });

            modelBuilder.Entity("PichangasApi.Models.PichangaMiembro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("JugadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PichangaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PichangaId");

                    b.ToTable("PichangaMiembros");
                });

            modelBuilder.Entity("PichangasApi.Models.SolicitudUnion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JugadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PichangaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PichangaId");

                    b.ToTable("SolicitudesUnion");
                });

            modelBuilder.Entity("PichangasApi.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Ataque")
                        .HasColumnType("integer");

                    b.Property<int>("Bloqueo")
                        .HasColumnType("integer");

                    b.Property<int>("Colocacion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Defensa")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Evaluado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Posiciones")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Recepcion")
                        .HasColumnType("integer");

                    b.Property<int>("Saque")
                        .HasColumnType("integer");

                    b.Property<int?>("TallaCm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PichangasApi.Models.Validacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmigoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ataque")
                        .HasColumnType("integer");

                    b.Property<int>("Bloqueo")
                        .HasColumnType("integer");

                    b.Property<int>("Colocacion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Defensa")
                        .HasColumnType("integer");

                    b.Property<Guid>("JugadorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Recepcion")
                        .HasColumnType("integer");

                    b.Property<int>("Saque")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AmigoId");

                    b.HasIndex("JugadorId");

                    b.ToTable("Validaciones");
                });

            modelBuilder.Entity("PichangasApi.Models.Pichanga", b =>
                {
                    b.HasOne("PichangasApi.Models.Usuario", "Admin")
                        .WithMany("PichangasAdministradas")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("PichangasApi.Models.PichangaMiembro", b =>
                {
                    b.HasOne("PichangasApi.Models.Usuario", "Jugador")
                        .WithMany("Membresias")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PichangasApi.Models.Pichanga", "Pichanga")
                        .WithMany("Miembros")
                        .HasForeignKey("PichangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Pichanga");
                });

            modelBuilder.Entity("PichangasApi.Models.SolicitudUnion", b =>
                {
                    b.HasOne("PichangasApi.Models.Usuario", "Jugador")
                        .WithMany("Solicitudes")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PichangasApi.Models.Pichanga", "Pichanga")
                        .WithMany("Solicitudes")
                        .HasForeignKey("PichangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Pichanga");
                });

            modelBuilder.Entity("PichangasApi.Models.Validacion", b =>
                {
                    b.HasOne("PichangasApi.Models.Usuario", "Amigo")
                        .WithMany("ValidacionesDadas")
                        .HasForeignKey("AmigoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PichangasApi.Models.Usuario", "Jugador")
                        .WithMany("ValidacionesRecibidas")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amigo");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("PichangasApi.Models.Pichanga", b =>
                {
                    b.Navigation("Miembros");

                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("PichangasApi.Models.Usuario", b =>
                {
                    b.Navigation("Membresias");

                    b.Navigation("PichangasAdministradas");

                    b.Navigation("Solicitudes");

                    b.Navigation("ValidacionesDadas");

                    b.Navigation("ValidacionesRecibidas");
                });
#pragma warning restore 612, 618
        }
    }
}
